name: Deploy

on:
  push:
    branches:
      - main

permissions:
  packages: write

env:
  IMAGE_TAG: dev${{ github.run_number }}

jobs:
  build:
    name: Build docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check yq version
        run: yq --version

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to ghcr.io
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64

  deploy:
    name: Update GitOps Repository
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          github-server-url: https://github.com
          repository: jaehong21/jaehong21-gitops
          ref: main
          token: ${{ secrets.GITOPS_TOKEN }}
          fetch-depth: 10

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Configure Git for GPG Signing
        run: |
          git config --global user.email "dev@jaehong21.com"
          git config --global user.name "jaehong21"
          git config --global commit.gpgSign true
          git config --global user.signingKey "${{ secrets.GPG_KEY_ID }}"

      - name: Update Kubernetes Manifest
        env:
          MANIFEST_PATH: workloads/book/deployment.yaml
        run: |
          # sed -i "s|image:.*|image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:$IMAGE_TAG|g" $MANIFEST_PATH
          # sed -i "s|version:.*|version: $IMAGE_TAG|g" $MANIFEST_PATH
          yq -i '.app.version = $IMAGE_TAG' $MANIFEST_PATH
          yq -i '.deployment.container.image.tag = $IMAGE_TAG' $MANIFEST_PATH

      - name: Commit and Push
        run: |-
          git commit -S -am "feat(book): update image to $IMAGE_TAG"
          git push -u origin main
